name: 🌿 PR이 생성될 때

on:
  pull_request:
    types: [opened]

jobs:
  link-related-issues:
    name: 🔗 관련 이슈를 연결한다
    runs-on: ubuntu-latest

    steps:
      - name: ① PR 이름에서 이슈 번호 찾기
        id: extract_issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -o -E "/#[0-9]+" | head -n 1 | tr -d '/#')
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_ENV

      - name: ② PR 내용에 resolves 이슈 번호 추가하기
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ env.issue_number }}
        run: |
          # PR 내용 가져오기
          PR_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.body')

          # resolves #이슈번호 붙이기
          NEW_PR_BODY="resolves #$ISSUE_NUMBER\n\n$PR_BODY"

          # PR 내용 업데이트
          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$NEW_PR_BODY\"}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
